config:
  renderer-infrastructure:cloud: aws # 'azure' | 'aws'
  renderer-infrastructure:projectName: puppeteer-renderer-comparison
  renderer-infrastructure:region: westeurope
  aws:region: eu-west-1
  azure-native:location: westeurope
  renderer-infrastructure:tags:
    owner: personal
    project: puppeteer-renderer
  renderer-infrastructure:renderer:
    containerImage: 263409072898.dkr.ecr.eu-west-1.amazonaws.com/pogodoc/renderer-puppeteer:latest
    containerPort: 8080
  renderer-infrastructure:ec2:
    instanceType: t3.medium
    amiId: ami-01f23391a59163da9
    sshCidr: 0.0.0.0/0
  renderer-infrastructure:lambda:
    memorySize: 1024
    timeout: 60
    handler: index.handler
    runtime: nodejs20.x
    packagePath: ../lambda-renderer-puppeteer/dist
  renderer-infrastructure:eks:
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    replicas: 2
    serviceType: NodePort
    nodePort: 30080
  azure-native:vmAdminPassword:
    secure: v1:9tHWZmve5PBE5+Ot:g+DyyuXuvghNfoMMA6J/2lAXoXsJAA7b
encryptionsalt: v1:42OJ5kQbinA=:v1:CqlWdg10YtU9UhtA:dpqBiP4ZL6n4FEGqObEZw0cOCWSH6w==
